name = "SymPyPythonCall"
uuid = "bc8888f7-b21e-4b7c-a06a-5d9c9496438c"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "0.4.0"


[deps]
CommonEq = "3709ef60-1bee-4518-9f2f-acd86f176c50"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SymPyCore = "458b697b-88f0-4a86-b56b-78b75cfb3531"

[compat]
CommonEq = "0.2.1"
CommonSolve = "0.2"
CondaPkg = "0.2"
LinearAlgebra = "1.6.1"
PythonCall = "0.9"
SpecialFunctions = "0.8, 0.9, 0.10, 1.0, 2"
SymPyCore = "0.2.5, 1"
TermInterface = "2"
julia = "1.6.1"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[targets]
test = ["Test", "LinearAlgebra", "SpecialFunctions", "TermInterface"]
